language: node_js
node_js:
  - "4.0.0"
  - "6.0.0"
  - "4"
  - "6"


# values taken from react-native's package.json
env:
  - REACT_NATIVE_VERSION=0.38 REACT_VERSION=15.4.0
  - REACT_NATIVE_VERSION=0.39 REACT_VERSION=15.4.0-rc.4
  - REACT_NATIVE_VERSION=0.40 REACT_VERSION=15.4.1
  - REACT_NATIVE_VERSION=0.41 REACT_VERSION=15.4.0
  - REACT_NATIVE_VERSION=0.42 REACT_VERSION=15.4.1


before_script:
  - npm uninstall react-native react react-dom react-addons-test-utils
  - npm install react@~$REACT_VERSION react-dom@~$REACT_VERSION react-addons-test-utils@~$REACT_VERSION react-native@~$REACT_NATIVE_VERSION
  - npm run build-haste
